### PR TITLE
fix for adding a 'similar' named search option

### PR DESCRIPTION
**Pull request by janmichaelyu**
Required for migrating from a direct fetch to extsimilar to using a custom constraint to get 'similar' results.

### CODE REVIEW

**Comment by janmichaelyu** [comment]
@grtjn Please review. :)

**Comment by grtjn** [comment]
Great reuse of the default search route! I still wonder if we need a separate search options for this, but looks great otherwise..

**Comment by grtjn** [comment]
hmm, we should have merged this. It starts showing commits from the next PR. Perhaps use feature branches next time.

**Comment by grtjn** [comment]
PR #9 includes changes of this PR, closing this one..

**Pull request closed without merging**
