### PR TITLE
Fix minimist vulnerability

### PR DESCRIPTION
**Pull request by crism**
This fixes issue #61 as well as other problems found with `npm audit`.

### CODE REVIEW

**Comment by crism** [comment]
This PR was against `master` instead of `development`.

**Comment by crism** [comment]
Reopening per suggestion from owners.

**Comment by BillFarber** [comment]
This PR is limited to updates to the dependency versions. Looks good to me.

**Comment by grtjn** [comment]
It seemed nodemon needed an update as well to get it fully clean, at least at my end.

Funny that doing an npm update in this repo resulted in 5 warnings that refused to get fixed, whereas updating only underscore, nodemon, and mocha, and some additional npm audit fix's worked fine.

**Comment by grtjn** [comment]
I pushed your changes together with the nodemon one into dev, and merged that into master. I think this PR is obsolete now..

**Comment by crism** [comment]
Thanks, @grtjn!

**Pull request closed without merging**
