### PR TITLE
add compression to the middle tier to gzip responses

### PR DESCRIPTION
**Pull request by Audarth**
Add compression middleware to nodeJS to compress data sent to the browser improving load times.

Default app goes from around 1.2MB downloaded to 300KB.

Larger apps such as my current one can go from 5.5MB to 1.6MB.

### CODE REVIEW

**Comment by grtjn** [comment]
Ha, love this one, seems so simple to add!

**Comment by grtjn** [comment]
I'd love to merge this one, but there is a merge conflict..

**Comment by grtjn** [comment]
By the way, might be best to work against 'development' branch next time.. ;)

**Comment by Audarth** [comment]
rebased to resolve the conflict

**Comment by grtjn** [comment]
I changed base to dev, not a bugfix..

**Comment by grtjn** [comment]
I wonder if we should suppress the lock file changes, but probably can't. Just thinking we ought to have control over it ourselves, make sure no mishap occurs. Then again it is going into dev anyhow, so perhaps that is good enough. We should run npm audit fix before landing into master by default perhaps.

@mariannemyers / @withjam : WDYT?

**Comment by grtjn** [comment]
Merging now..

**Pull request merged**
