### PR TITLE
GROVE-531: added /facets and /results to default search route

### PR DESCRIPTION
**Pull request by mariannemyers**
Original Title: added handling of /facets and /results to default search route
Migrated from BitBucket 15 April 2019

Prior comment from @grtjn 
Some testcases to go with this would be nice, but I might need an extra pair of eyes for that. Feel free to pile on top.. 🙂

### CODE REVIEW

**Comment by withjam** [comment]
We definitely need some test cases for this to make sure new stuff works and original search remains unchanged.

**Comment by grtjn** [comment]
I have used this in at least 2 demos with great success, but I agree that having some test cases for this would be great. Who is good at writing them? I am not feeling very confident with them, could likely use some help..

**Comment by grtjn** [comment]
I pushed changes that include tests for the search api into the testing PR of grove-core-api. Maybe start with some extra test cases there? I'll also check if I opened a PR against grove-vue-ui yet, that would make use of this.

**Comment by grtjn** [comment]
not sure if there were merge conflicts, but my local git clone was behind, so i synched, rebased and pushed just to be sure..

**Comment by grtjn** [comment]
Grr, why is VS Code automatically merging PRs!!

**Pull request merged**
